### ISSUE TITLE
Admin - Gallery Custom Post: Please remove the WYSIWYG since it is not necessary anymore.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Luxuride#36]
![image](https://cloud.githubusercontent.com/assets/13363508/14451164/6a9e19d4-00b7-11e6-843e-5169692186bf.png)

**Comment by joancapuyan** [comment]
As per Jolene, she suggested to just use Gallery ACF for Gallery page and for homepage and sidebar.
