### ISSUE TITLE
Banner: Project Scope mentioned the embed options, is it editable in the video URL or it should be hard-coded? Please clarify. Thanks

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Luxuride#42]
![image](https://cloud.githubusercontent.com/assets/13363508/14451988/df4051ca-00bd-11e6-988f-2c4aa101f1f9.png)

**Comment by joancapuyan** [comment]
The video options can be edited at the Titan Options. The youtube field in the Business details will be a plain video URL.
