### ISSUE TITLE
Lead-ins: "Read More" text link isn't existing as per design, and it is mentioned in scope, which I believe this is a scope error. 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Luxuride#47]
![image](https://cloud.githubusercontent.com/assets/13363508/14453242/311d6566-00c6-11e6-978c-6cfc77c91c99.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14453252/4bcfc804-00c6-11e6-8458-e0198d3d520b.png)

**Comment by joancapuyan** [comment]
Yes it is a scope error and I already removed the field.
