### ISSUE TITLE
Homepage - Benefits: When title is empty, post item will be completely hidden in the front-end.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Luxuride#48]
![image](https://cloud.githubusercontent.com/assets/13363508/14453722/05c73bc8-00c9-11e6-9349-4f05dda0bf32.png)

**Comment by joancapuyan** [comment]
As per the standards and guidelines "Repeater: If the field is not marked as *required and it is blank, hide the section but display the other fields", but I can completely hide it if needed.
