### ISSUE TITLE
Homepage - Content: Titan Read Slide More isn't implemented.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Luxuride#51]
![image](https://cloud.githubusercontent.com/assets/13363508/14454187/b1fedd7c-00cb-11e6-950b-5c4ac6a263b0.png)

**Comment by joancapuyan** [comment]
The Titan Read Slide More was already implemented, it doesn't work because the content they added is wrapped by two divs only and the plugin works if there is at least 3 html elements.
