### ISSUE TITLE
W3C - Homepage: 2 Errors

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Luxuride#59]
![image](https://cloud.githubusercontent.com/assets/13363508/14807649/e6b32ce0-0bb0-11e6-9438-3367df3321d7.png)

**Comment by joancapuyan** [comment]
User error from homepage content with html tags inside.

![image](https://cloud.githubusercontent.com/assets/18027230/14808637/868be1be-0bb9-11e6-802f-c10d9f880fca.png)
